[DEBUG] Dokka not working
https://github.com/hossain-khan/kgeo-device-timeline/actions/runs/11307016369/job/31448265608

```
Run git config --global user.name 'github-actions[bot]'
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
 modified:   gradlew

no changes added to commit (use "git add" and/or "git commit -a")
Error: Process completed with exit code 1.
```